# Generated by Django 4.2.5 on 2023-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_category_userprofile_user_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
